### ISSUE TITLE
Django 4.0 compatibility

### ISSUE THREAD

**Issue by squio** [percipient/django-allauth-2fa#116]
Django 4.0 has reached beta testing and will be release before the end of 2021

Some deprecated utilities have been removed:

- `url` - use `path` instead
- `force_text` in favor of `force_str`

**Comment by valberg** [comment]
This would mean that we should drop support for Django <= 1.11 - which frankly sounds like a good idea to me :)

**Comment by akx** [comment]
Absolutely. I see no reason for a security-oriented library to support a version of Django that is way out of date.

**Comment by squio** [comment]
Quick heads-up: is it possible to release a 0.9 intermediate version for Django 4.0?
Current Pypi version is still 0.8 https://pypi.org/project/django-allauth-2fa/

**Comment by akx** [comment]
@squio Yes, but #125 should probably be resolved for that version (since I bumped into it trying to upgrade a project to Django 4.0).

**Comment by akx** [comment]
I cut a 0.9rc1 release from cd2d5314a635ef1a62e1ff3ae10ba64730780ad8 and pushed it to PyPI: https://pypi.org/project/django-allauth-2fa/0.9rc1/

If you can, please give it a shot (you may need to do `pip install --pre django-allauth-2fa==0.9rc1` or similar since it indeed is a pre-release).

If there are no issues, I can push a real 0.9 release soon. :)

**Comment by clokep** [comment]
> I cut a 0.9rc1 release from [cd2d531](https://github.com/valohai/django-allauth-2fa/commit/cd2d5314a635ef1a62e1ff3ae10ba64730780ad8) and pushed it to PyPI: [pypi.org/project/django-allauth-2fa/0.9rc1](https://pypi.org/project/django-allauth-2fa/0.9rc1/)

Please do push tags to the repo also, it is useful for tracking how packages were built! 👍

**Comment by akx** [comment]
@clokep Ah yeah, sure :) https://github.com/valohai/django-allauth-2fa/releases/tag/v0.9rc1

**Comment by clokep** [comment]
Thank you!

Also, glad you got a release working! 👍 🎉

**Comment by akx** [comment]
@squio et al.: have you had the time to try 0.9rc1?

**Comment by squio** [comment]
@akx I'm currently using my own fork which contains all the changes in the 0.9 branch as far as I can tell: https://github.com/valohai/django-allauth-2fa/compare/v0.9rc1...squio:main

This works perfectly well for our use case (in production!) 👍

**Comment by valberg** [comment]
Should we get 0.9 out?

**Comment by akx** [comment]
@valberg Sorry, I had totally missed that message. Cutting 0.9 now :)

**Comment by akx** [comment]
Version 0.9 is compatible with Django 4.0. :)
